test: &default

  # Credentials for REST APIs
  client_id: <%= Figaro.env.paypal_client_id %>
  client_secret: <%= Figaro.env.paypal_client_secret %>

  # Mode can be 'live' or 'sandbox'
  mode: sandbox

  # Credentials for Classic APIs
  app_id: APP-80W284485P519543T
  username: <%= Figaro.env.paypal_username %>
  # jb-us-seller_api1.paypal.com
  password: <%= Figaro.env.paypal_password %>
  # WX4WTU3S8MY44S7F
  signature: <%= Figaro.env.paypal_signature %>
  # AFcWxV21C7fd0v3bYYYRCpSSRl31A7yDhhsPUU2XhtMoZXsWHFxu-RWy
  # # With Certificate
  # cert_path: "config/cert_key.pem"
  sandbox_email_address: <%= Figaro.env.paypal_sandbox_email %>
  # Platform.sdk.seller@gmail.com

  # # IP Address
  # ip_address: 127.0.0.1
  # # HTTP Proxy
  # http_proxy: http://proxy-ipaddress:3129/

development:
  <<: *default

production:
  <<: *default
  mode: live
